### ISSUE TITLE
How to convert an "old" gzip file to "new" gzip file?

### ISSUE THREAD

**Issue by buom** [eBay/GZinga#1]
Thank for your nice work :)
Please tell me how to convert _old_ GZIP file (non-seekable + none-splittable) to _new_ GZIP file (seekable + splittable)?

**Comment by r4ruchir** [comment]
Thanks for your comment.
I would suggest to read your old GZIP file (using GZIPInputStream) and convert it into new format using GZipOutputStreamRandomAccess.

**Comment by buom** [comment]
Thanks for your suggestion :)
