### ISSUE TITLE
main's Deferring to super?

### ISSUE THREAD

**Issue by garyschulte** [eBay/GZinga#2]
the main methods of both the GZipInputStreamRandomAccess and GZipOutputStreamRandomAccess both simply defer to GZIPInputStream and GZIPOutputStream in their respective main() methods -    Is there a reason for this?

**Comment by r4ruchir** [comment]
@garyschulte : There was no particular reason and it was used for some testing purpose only. I have modified main method to use direct GZipInputStreamRandomAccess and GZipOutputStreamRandomAccess classes. Also for usage purpose, you can refer to test methods.
