### ISSUE TITLE
Indexed gzip files are not portable across different systems.

### ISSUE THREAD

**Issue by brahul** [eBay/GZinga#3]
GZinga files which are generated/created from windows systems aren't readable by readers/apps in unix flavour systems.
Reverse is also true. These files should be portable.

Validity is confirmed by looking for the exact header bytes , this should ideally ignore the os related metadata (byte index 9 and 10).

**Comment by rucshah** [comment]
@brahul : thanks for your input. Will you able to create PR for same?

**Comment by brahul** [comment]
@ I have submitted a pull request. thanks!

**Comment by brahul** [comment]
@rucshah Thanks for merging the pull.
